#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

polybar example &

feh --bg-fill /home/arch-goat/Pictures/1141085.jpg

bspc monitor -d what the sigma

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

